name: pcfm_odd_finetuning_D10k
result_path: results/odd_finetuning/D10k

data:
  data_file: data/odd_finetune_150k.h5
  batch_size: 256
  batch_size_val: 4096
  val_samples: 5000
  max_samples: 10000
  use_nlayers_conditioning: true
  use_direction_conditioning: true
  transform_num_points:
    - [Log, {alpha: 0.5}]
    - [StandardScaler, {shape: [1, 48]}]
  transform_fsamp:
    - [MinMaxScaler, {shape: [1, 1], target_min: -1.0, target_max: 1.0}]
  transform_nlayers:
    - [MinMaxScaler, {shape: [1, 1], target_min: -1.0, target_max: 1.0}]

model:
  name: FullyConnected
  dim_input: 48
  dim_condition: 6
  dim_time: 6
  hidden_dims: [128, 256, 512, 256, 128]
  dropout: 0.1

training:
  pretrain_weights: results/pretrain_SimpleBox/best_model.pt
  use_pretrain_transforms: true
  reset_output_layer: false
  epochs: 3000
  patience: 3000
  physics_patience: 50
  test_every: 20
  optimizer:
    name: AdamW
    lr: 1.0e-4
    weight_decay: 5.0e-4
  scheduler:
    name: CosineAnnealingLR
    T_max: 500
    eta_min: 1.0e-6
