name: pcfm_simplebox_finetuning_D100
result_path: results/simplebox_finetuning/D100

data:
  data_file: data/simplebox_finetune_100k.h5
  batch_size: 16
  batch_size_val: 1024
  val_samples: 5000
  max_samples: 100
  use_nlayers_conditioning: true
  use_direction_conditioning: true
  transform_num_points:
    - [Log, {alpha: 0.5}]
    - [StandardScaler, {shape: [1, 45]}]
  transform_fsamp:
    - [MinMaxScaler, {shape: [1, 1], target_min: -1.0, target_max: 1.0}]
  transform_nlayers:
    - [MinMaxScaler, {shape: [1, 1], target_min: -1.0, target_max: 1.0}]

model:
  name: FullyConnected
  dim_input: 45
  dim_condition: 6
  dim_time: 6
  hidden_dims: [128, 256, 512, 256, 128]
  dropout: 0.0

training:
  pretrain_weights: results/pretrain_SimpleBox/best_model.pt
  use_pretrain_transforms: true
  reset_output_layer: false
  epochs: 8000
  patience: 3000
  physics_patience: 50
  test_every: 20
  optimizer:
    name: AdamW
    lr: 1.0e-6
    weight_decay: 5.0e-3
